name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
        with:
          node-version: '16'

      - name: Build
        run: |
          npm i && npm run build
          
      - name: Publish
        run: |
          rm -rf public
          git clone "https://${{ secrets.DEPLOY }}@github.com/vicimpa/vicimpa.github.io.git" public
          cd public
          rm -rf regions-city
          mv ../dist regions-city
          git add regions-city/*
          git config --global user.email "vicimpa@ya.ru"
          git config --global user.name "PromiSe####"
          COMMIT_MESSAGE="Update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git commit -m "${COMMIT_MESSAGE}"
          git push
